# Generated by Django 4.0.3 on 2022-03-17 17:57

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_origin_snapurl_hash_snapurl_origin_snapurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(max_length=200, validators=[core.validators.uri_validator]),
        ),
        migrations.AlterField(
            model_name='snapurl',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
