# Generated by Django 4.0.3 on 2022-03-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_snapurl_hash_alter_snapurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapurl',
            name='hash',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='snapurl',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
